const STEPS = [
  {
    key: 'task',
    shortTitle: '任务描述',
    title: '你要做什么？',
    subtitle: '一句话描述你想外包的任务',
    explain: '写下任务名称，越具体越好。AI 会根据你的描述拆解成可执行的小步骤。',
    type: 'text',
    placeholder: '准备周五课堂演讲、整理书架、规划下周读书计划...',
  },
  {
    key: 'deadline',
    shortTitle: '截止时间',
    title: '什么时候截止？',
    subtitle: '设定一个时间锚点',
    explain: '给任务一个明确的截止点，没有时限的任务永远做不完。',
    type: 'radio',
    options: [
      { value: 'today', label: '今天' },
      { value: 'tomorrow', label: '明天' },
      { value: 'this_week', label: '本周内' },
      { value: 'custom', label: '自定义' },
    ],
  },
  {
    key: 'progress',
    shortTitle: '当前进度',
    title: '现在进度如何？',
    subtitle: '如实回答，不用修饰',
    explain: '诚实面对现在的状态，从真实起点出发的方案才有用。',
    type: 'radio',
    options: [
      { value: 'not_started', label: '完全没开始', desc: '白纸一张' },
      { value: 'ideas', label: '有一些想法/素材', desc: '脑子里有但没动笔' },
      { value: 'half_way', label: '做了一半', desc: '卡在半路' },
      { value: 'almost_done', label: '快完成了', desc: '差收尾' },
    ],
  },
  {
    key: 'bottleneck',
    shortTitle: '卡点分析',
    title: '卡在哪里？',
    subtitle: '找到那个真正阻碍你的点',
    explain: '定位真正的阻碍，AI 才能针对性地帮你绕过或拆解它。',
    type: 'radio',
    options: [
      { value: 'start', label: '不知道从哪开始', desc: '启动困难' },
      { value: 'info', label: '信息/资料不够', desc: '手头缺东西' },
      { value: 'direction', label: '方向不清晰', desc: '不知道往哪走' },
      { value: 'motivation', label: '就是不想动', desc: '纯粹没动力' },
      { value: 'fear', label: '怕做不好', desc: '完美主义拖延' },
    ],
  },
  {
    key: 'resources',
    shortTitle: '已有资源',
    title: '手头有什么？',
    subtitle: '已有的材料、工具、半成品、参考...',
    explain: '盘点现有资源，AI 会优先利用已有基础，减少从零开始的工作。',
    type: 'textarea',
    placeholder: '例如：有一份去年的PPT可以参考、电脑里存了资料...（可选）',
  },
  {
    key: 'importance',
    shortTitle: '重要程度',
    title: '这件事有多重要？',
    subtitle: '帮你定优先级',
    explain: '区分紧急与重要，AI 会根据重要程度调整拆解粒度和提醒频率。',
    type: 'radio',
    options: [
      { value: 'urgent', label: '紧急重要', desc: '不做得完蛋' },
      { value: 'important', label: '重要不紧急', desc: '做了有长远收益' },
      { value: 'optional', label: '做不做都行', desc: '佛系' },
    ],
  },
  {
    key: 'remind_mode',
    shortTitle: '提醒方式',
    title: '需要外力督促吗？',
    subtitle: '选择提醒方式',
    explain: '选择是否需要飞书推送提醒，或只查看拆解结果自行执行。',
    type: 'radio',
    options: [
      { value: 'lark', label: '拆解并推送到飞书提醒', desc: '我需要外部督促' },
      { value: 'self', label: '只拆解，不推送', desc: '我自己能搞定' },
    ],
  },
];

export default STEPS;
